In [1]:
! pip3 install numpy

In [2]:
import numpy as np

In [ ]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [4]:
x=np.array((1,2,3,4,5))
print(x)

[1 2 3 4 5]


In [7]:
print(np.arange(20,-21,-10))


[ 20  10   0 -10 -20]


In [8]:
a=np.arange(4)
print(a)

[0 1 2 3]


In [9]:
a=np.arange(4,1)
print(a)

[]


In [10]:
#creates array with random values
a1=np.random.random(size=(4,6))
a1

array([[2.79562847e-01, 6.03676863e-01, 1.38145115e-01, 9.15742832e-01,
        4.17396455e-02, 5.16057749e-01],
       [9.87154934e-01, 4.94098478e-01, 3.37718769e-01, 1.33838762e-01,
        2.82043718e-01, 3.66755148e-01],
       [2.27358146e-01, 2.38965556e-01, 5.50233131e-01, 5.86774345e-01,
        2.23027024e-01, 7.15214149e-01],
       [3.46602945e-01, 4.60219697e-01, 3.24506036e-01, 1.25671741e-01,
        2.13011010e-01, 8.07924477e-04]])

In [28]:
a=np.random.randint(low=20,high=30,size=(2,3))
a

array([[29, 26, 27],
       [22, 21, 24]])

In [29]:
arr= np.array((1,2,3,4,5))
print(arr)
print('dimension:',arr.ndim)

[1 2 3 4 5]
dimension: 1


In [36]:
a=np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [40]:
a=np.arange(4,49,4).reshape(3,4)
print(a)


[[ 4  8 12 16]
 [20 24 28 32]
 [36 40 44 48]]


In [ ]:
arr1=np.arange(10)
arr2=a=np.arange(20).reshape(3,4)
arr3=np.arange(20).reshape(2,4,3)

In [ ]:
print(arr1[::])

In [4]:
import numpy as np

In [5]:
x=np.array((1,2,3,4,"hello"))
print(x)


['1' '2' '3' '4' 'hello']


In [8]:
a1=np.array((1,2,3,4))
a2=np.array((1.1,2.2,3.3,4.4))
print(a1.dtype)
print(a2.dtype)
print(a1.itemsize)
print(a2.itemsize)


int32
float64
4
8


matrices

In [ ]:
print(np.zeros(10))
print(np.zeros((3,6)))
print()
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [10]:
print(np.ones(10))
print(np.ones((3,6)))
print()
print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.identity(0)

array([], shape=(0, 0), dtype=float64)

In [17]:
a1=np.array([1,3,5,7])
b1=np.array([2,4,6,8])
print()

In [13]:
a1=np.array([2,4,5,7,8,4,1,5,6])
for i in a1:
    print(i)

2
4
5
7
8
4
1
5
6


In [ ]:
s1=np.arange(12).reshape(3,4)
s2=np.arange(12,24).rshape(4,5)
print(s1,s2)

In [ ]:
s3=0

In [ ]:
np.hsplit(s3,2)

In [19]:
arr2= np.arange(12).reshape(4,3)
print(arr2)
print("shape of array:", arr2.shape)
print("Number of dimentions :",arr2.ndim,end='\n\n')


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
shape of array: (4, 3)
Number of dimentions : 2



In [1]:
#assignments:
import numpy as np
board =np.arange(16).reshape(4,4)
print("full board:\n", board)
sub_board= board[2:4,2:4]
print("\nbottom-right 2x2 sub board:\n", sub_board)

full board:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

bottom-right 2x2 sub board:
 [[10 11]
 [14 15]]


In [3]:
arr=np.random.randint(10,51,20)
print("original array\n",arr)
result=arr[1::2]
print("sliced array",result, end=" ")

original array
 [18 34 40 38 32 33 17 30 14 10 42 36 49 34 23 39 43 26 31 27]
sliced array [34 38 33 30 10 36 34 39 26 27] 

In [4]:
matrix=np.arange(16,32).reshape(4,4)
print("full matrix",matrix)
sub_matrix= matrix[1:3,1:3]
print("sub matrix :", sub_matrix)

full matrix [[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
sub matrix : [[21 22]
 [25 26]]


In [7]:
arr=np.random.randint(0,100, (4,4,4))
print("random matrix",arr)
sub_matrix=arr[1:3,1:3,1:3]
print("sub_matrix",sub_matrix)

random matrix [[[93 78 97 48]
  [61 49 33  5]
  [82 39 44 32]
  [32 63 84 97]]

 [[70 37 53 10]
  [49 98 56 10]
  [81 93 57 30]
  [83 65 29 24]]

 [[84 75 66  5]
  [75  8 10 32]
  [24 84  6 24]
  [ 0 11 67 52]]

 [[64 92 27  5]
  [54 51 77 56]
  [62 97  5 53]
  [75 88 73 75]]]
sub_matrix [[[98 56]
  [93 57]]

 [[ 8 10]
  [84  6]]]


In [10]:
arr=np.random.randint(0,21,(4,4))
print("arr",arr)
arr[arr %2 !=0]=-1
print("replaced array",arr)

arr [[12  7  3 10]
 [ 4 16  5  6]
 [18 15 13 18]
 [ 5  2 13 20]]
replaced array [[12 -1 -1 10]
 [ 4 16 -1  6]
 [18 -1 -1 18]
 [-1  2 -1 20]]


In [11]:
scoreboard=np.arange(1,50).reshape(7,7)
print("scorboard",scoreboard)
main_diag=np.diag(scoreboard)
print("diagonaal elements",main_diag)

scorboard [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]
diagonaal elements [ 1  9 17 25 33 41 49]


In [18]:
x = int(input("enter the shape value:"))
y = int(input("enter the shape value:"))
arr=np.random.randint(1,50,(x,y))
print("random array",arr)
avg=np.mean(arr)
print("the avg of array element",avg)

random array [[32 44 35 47 11 22]
 [38 41  5  1 33 49]
 [20 40  4 11 45 31]
 [34 16 25  3 17 48]
 [ 1 10 40 27  5  9]]
the avg of array element 24.8


In [19]:
vector=np.zeros(10)
vector[4]=1
print("main vector is: ", vector)

main vector is:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
arr=np.random.randint(1,50,(5,5))
print("matrix",arr)

matrix [[25 26 26 21  1]
 [ 8  2 45 12 14]
 [45 49 39 45  5]
 [17 22  9 33 46]
 [32 49 28 20 37]]


In [3]:
import numpy as np
arr2=np.arange(24).reshape(6,4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [5]:
arr2[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [7]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
arr2[:,[0,3,1]]

array([[ 0,  3,  1],
       [ 4,  7,  5],
       [ 8, 11,  9],
       [12, 15, 13],
       [16, 19, 17],
       [20, 23, 21]])

In [9]:
arr2[:,[1,2,3]]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [14]:
arr2>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
arr2[arr2>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [19]:
arr2[(arr2>15) & (arr2 % 2 !=0)]

array([17, 19, 21, 23])

In [20]:
arr2[arr2 % 4 ==0]

array([ 0,  4,  8, 12, 16, 20])

In [21]:
arr1=np.arange(12).reshape(4,3)
arr2=np.arange(4)
print(arr1,arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] [0 1 2 3]


In [23]:
arr1=np.arange(12).reshape(4,3)
arr2=np.arange(4).reshape(1,1,4,1)
#print(arr1,arr2)
res1= arr1+arr2
res1

array([[[[ 0,  1,  2],
         [ 4,  5,  6],
         [ 8,  9, 10],
         [12, 13, 14]]]])

In [ ]:
# broadcasting in numpy 


In [27]:
arr1=np.arange(4).reshape(4,1)
arr2=np.arange(4).reshape(1,4)
print(arr1,arr2)
res1= arr1+arr2
res1

[[0]
 [1]
 [2]
 [3]] [[0 1 2 3]]


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [34]:
a=np.arange(5,10).reshape(5,1)
b=np.arange(10,6,-1).reshape(1,4)
print(a+b)


[[15 14 13 12]
 [16 15 14 13]
 [17 16 15 14]
 [18 17 16 15]
 [19 18 17 16]]


In [36]:
np.isnan(arr1)

array([[False],
       [False],
       [False],
       [False]])